---
title: "About Us"
output: 
  html_document:
    toc: true
    toc_float: true
---


Hi, we are Shina, Pavithra and Jenna from p8015 Fall 2!

Thank you for viewing our website :) Feel free to learn more about us by our socials linked below:

### [Shina Min](https://shinamin0218.github.io/)

Hello fellow Public Health students~ my name is Shina Min and I am currently pursuing a Master's degree in Epidemiology at Columbia University with a strong interest in the fields of aging, and chronic diseases, espically Alzheimer's disease!

Fun Fact: My favorite movie is La La Land!

[Linkedin](https://www.linkedin.com/in/shina-min-3b7b58113/) | [Email](sm5567@cumc.columbia.edu)

### [Jenna Mohammed](Jenna-Mohammed.github.io)

Hi! My name is Jenna Mohammed, and I am a first year MS student studying Epidemiology at the Mailman School of Public Health. I have a strong interest in Psychiatric and Neurological Epidemiology, specifically with underrepresented populations :)

Fun Fact: I play cello!!

[Linkedin](https://www.linkedin.com/in/jenna-mohammed-03601a1aa/) | [Email](jam2530@cumc.columbia.edu)


### Pavithra 


