---
title: "Introduction"
output: 
  html_document:
    toc: true
    toc_float: true
---


Both substance abuse and maternal/infant mortality run rampant in the United States, and with the the use of the CDC 2007 PRAM Data set, we are interested in looking at the relationships between these variables. 


## Initial questions

##### Our initial research question
Is there a significant relationship between infant mortality rate and the consumption of Alcohol and Tobacco consumption?

##### How did these questions evolve over the course of the project?
Upon reviewing reviewing the 2007 CDC PRAM data set, and thoroughly understanding the data, we picked our variables of interest that we wanted to test. The data provides robust information on several important factors related to maternal and infant health outcomes. 

##### What new questions did you consider in the course of your analysis?
Other parts of the data that interested us was also the use of contraception in the sample demographic. 


## Motivation for this Project
We are interested in looking at how pregnancy outcomes changes among mothers who drank or smoked cigarettes before conception, and comparing it to mothers who did not abuse any substances. As a group, we were collectively interested in both Maternal Child Health and Substance Abuse and this was an ideal way to combine those two interests. The demographics, social dynamics, and healthcare system in the United States provide a unique perspective on the outcomes of maternal health and substance abuse. We are interested in learning more about the relationship between substance abuse and infant mortality rates. 


## Related Work

* Alcohol use during pregnancy
  - The negative impact of smoking during pregnancy is evident in its direct association with adverse birth outcomes. This habit has been linked to a range of complications, including damage to the umbilical cord structure, an elevated risk of miscarriage and ectopic pregnancy, as well as an increased likelihood of low birthweight, placental abruption, preterm birth, and heightened infant mortality rates. (https://pubmed.ncbi.nlm.nih.gov/17884310/)
  - According to Wolfe et al., within a dataset comprising 4,536,701 birth records, 1.20% exhibited diagnostic codes related to drug or alcohol discharge (n = 54,290). The unadjusted Relative Risks (RRs) for maternal (RR = 2.7), fetal (RR = 1.3), neonatal (RR = 2.4), and postneonatal (RR = 4.3) mortality were elevated among births diagnosed with drug or alcohol-related conditions.(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3349286/)
  

* Tobacco use during pregnancy
  - The consumption of alcohol during pregnancy has been correlated with a spectrum of adverse birth outcomes. This includes heightened risks of miscarriage, stillbirth, infant mortality, congenital anomalies, low birthweight, reduced gestational age, preterm delivery, and infants being born small for their gestational age. (https://pubmed.ncbi.nlm.nih.gov/19797967/)
  - While specific data on infant mortality rates was not explicitly provided, it is noteworthy that maternal smoking during pregnancy constitutes a well-established risk factor for sudden unexpected infant death (SUID). The risk of SUID more than doubled (adjusted odds ratio [aOR] = 2.44; 95% confidence interval [CI] 2.31–2.57) in the presence of any maternal smoking during pregnancy. Furthermore, a twofold increase in SUID risk was observed when comparing no smoking to smoking just 1 cigarette daily throughout pregnancy. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6564075/)






