---
title: "Proposal"
output: 
  html_document:
    toc: true
    toc_float: true
---

## FINAL PROJECT- P8105

```{r echo = FALSE}
group_members =
  data.frame(
  Names = c("Jenna Mohammed", "Shina Min", "Pavithra Srinivasan"),
  Emails = c("jam2530@cumc.columbia.edu", "sm5567@cumc.columbia.edu", "ps3414@cumc.columbia.edu"),
  UNI = c("jam2530", "sm5567", "ps3414")
)
knitr::kable(group_members, format = "markdown", col.names = c("Names", "Emails", "UNI"))
```


## Project Title
* Looking at Infant Mortality Outcomes in relation to Alcohol and Tobacco Consumption

## Motivation for this Project
* Interested in looking at how pregnancy outcomes changes among mothers who drank or smoked cigarettes 3 months before conception, and during pregnancy and comparing it to mothers who did not abuse any substances. As a group, we were collectively interested in both Maternal Child Health and Substance Abuse and this was an ideal way to combine those two interests. The demographics, social dynamics, and healthcare system in NYC provide a unique perspective on the outcomes of maternal health and substance abuse. We are interested in learning more about the relationship between substance abuse and pregnancy as it is rampant and detrimental to health outcomes. 

## Intended Final Products
Creating a website:

* Using Plotly to create graphs comparing the different data sets
* Pages explaining the background of substance abuse in pregnancy - alcohol consumption and cigarette use in NYC
  - CDC birth defects:https://www.cdc.gov/ncbddd/
* About page: brief intro about Jenna, Shina and PavPerform a statistical analysis of the provided data

* All graphs and results in a pdf (specific comparisons stated in planned analyses)
* Github repo

## The anticipated data sources
* Data from NYC Health
  - 2007 data Women who drank any alcohol three months prior to conception
  - 2007 data Women who drank any alcohol during the last three months of pregnancy
  - 2007 data Women who stopped drinking alcohol during pregnancy
  - 2007 data Women who smoked any cigarettes three months prior to conception
  - 2007 data Women who smoked any cigarettes during the last three months of pregnancy
  - 2007 data Women who stopped smoking during pregnancy
* CDC PRAMStat Data for 2007

## The planned analyses / visualizations / coding challenges
* Data Manipulation: To compare and contrast the different data sets
  - Compare the ages of pregnant women with the highest and lowest substance usage
  - Compare maternal use of substances in different boroughs
  - Compare outcomes of birth defects with mothers who stopped smoking/drinking to those who continued smoking/drinking during pregnancy
* Visualization: ggplots (histograms, bar graph, scatter plot, density plot, and line graphs)
* Coding challenges: Hypothesis testing, linear and logistic regression, using patchwork to combine data sets, creating a website, and formatting for aesthetics. 


## The planned timeline
* Planning (1st week)
  - Define the project scope and goals 
  - Plan the site structure and features
  - Assign roles and responsibilities to team members 
* Project review meeting (11.16.23)
* Data Analysis (2nd week)
  - Tidy, and combine data sets to see trends in pregnancy outcomes
  - Create plots and write interpretations
* Design the website (3rd week)
  - Create a landing page and background pages
  - wireframes and mockups 
  - Create visual designs and format aesthetics
* Finalizing (4th week)
  - Run through any coding/knitting issues
  - Ensure everything is finalized to submit and work on in-class presentation doc. 

